# Generated by Django 4.1.3 on 2022-11-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=64)),
                ('direction', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
